# Generated by Django 4.0.6 on 2022-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('path', models.ImageField(upload_to='uploads/Banner')),
                ('url', models.CharField(max_length=200)),
                ('position_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
