# Generated by Django 4.0.6 on 2022-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('position_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('label', models.CharField(max_length=100)),
                ('audiolink', models.FileField(upload_to='')),
            ],
        ),
    ]
