# Generated by Django 4.0.6 on 2022-07-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0003_model_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='symposium.rule')),
            ],
        ),
    ]
