# Generated by Django 4.0.6 on 2022-07-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0004_rule_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('modellink', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('label', models.CharField(max_length=100)),
                ('audiolink', models.FileField(upload_to='')),
                ('model_displayed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='symposium.model_all')),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='rule',
        ),
        migrations.DeleteModel(
            name='Model_Display',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
