# Generated by Django 4.0.6 on 2022-07-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0005_model_all_point_remove_channel_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='model_displayed',
        ),
        migrations.AddField(
            model_name='model_all',
            name='point_link',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='symposium.point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_all',
            name='description',
            field=models.TextField(),
        ),
    ]
