# Generated by Django 4.0.6 on 2022-07-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0006_remove_point_model_displayed_model_all_point_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_all',
            name='point_link',
        ),
        migrations.AddField(
            model_name='point',
            name='model_link',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='symposium.model_all'),
            preserve_default=False,
        ),
    ]
