# Generated by Django 4.0.6 on 2022-07-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0007_remove_model_all_point_link_point_model_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_all',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
