# Generated by Django 4.0.6 on 2022-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0008_model_all_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_all',
            name='modellink',
            field=models.FileField(upload_to='uploads/Models'),
        ),
        migrations.AlterField(
            model_name='model_all',
            name='slug',
            field=models.SlugField(editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='point',
            name='audiolink',
            field=models.FileField(upload_to='uploads/Models/Points'),
        ),
        migrations.AlterModelTable(
            name='model_all',
            table='Models',
        ),
    ]
