# Generated by Django 4.0.6 on 2022-07-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0009_alter_model_all_modellink_alter_model_all_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model_all',
            table=None,
        ),
    ]
