# Generated by Django 3.2.13 on 2022-07-24 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0012_navlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='rotation_x',
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='rotation_y',
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='rotation_z',
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
