# Generated by Django 3.2.13 on 2022-07-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0013_auto_20220724_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='rotation_x',
            new_name='rotation',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='rotation_y',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='rotation_z',
        ),
    ]
